### PR TITLE
fix: enable eslint #19

### LINKED ISSUE #19: Improve linting
# Bug Report
## Description 

Requires some investigation to be sure this is an issue. Currently it may be the case that the linter isn't working correctly for the client / react code, e.g. it may be missing rule violations. Resarch this issue and resolve.

### PR DESCRIPTION
**Pull request by aakhtar3**
# Pull Request (PR) - *enable eslint*

https://github.com/JRIngram/leitner/issues/19

## Description of Change

    Give I am the owner of this repository,
    Then I would like to run lint,
    So that code meets a style.

## How to test this change

run `npx eslint .`

### Checklist for developer of feature
- [ x] I have performed a code review on my own code
- [ x] I have written unit tests to test my code, either with jest or react testing library
- [ x] I have linked to the appropriate issue on GitHub
- [ x] I have written an appropriate description for this PR.
- [ x] I have written how to test this PR.
- [ x] I have updated the documentation (JSDoc / README etc.) where appropriate
- [ x] I have commented my code.
- [ x] I have updated the changelog.

### Checklist for reviewers
- [x ] I have reviewed the new code
- [ x] I have checked that new unit tests have been written
- [ x] I have ran the unit tests and they pass.
- [ x] I have followed the given steps to test the PR

### CODE REVIEW

**Comment by aakhtar3** [comment]
@JRIngram Fixed the issue with running eslint.

**Comment by JRIngram** [comment]
@aakhtar3 fantastic thank you so much! If you could update the CHANGELOG.md file that would be great, then I'll merge and I can fix the linting issues on a separate branch. 
Thanks again 😄

**Comment by aakhtar3** [comment]
@Jacoberson added to CHANGELOG.md

**Review by JRIngram — APPROVED** [review]
Thank you so much for this mate!

**Pull request merged**
